<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\LiqPay\Form\Element;

use MSBios\LiqPay\RuntimeException;
use Zend\Form\Element\Hidden;
use Zend\Json\Json;

/**
 * Class Data
 * @package MSBios\LiqPay\Form\Element
 */
class Data extends Hidden
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $value
     * @return \Zend\Form\Element
     */
    public function setValue($value)
    {
        if (!is_array($value)) {
            throw new RuntimeException('Value must be array');
        }

        /** @var string $value */
        $value = base64_encode(Json::encode($value));

        return parent::setValue($value);
    }


}